### ISSUE TITLE
Wiki - Details persos lien tutos

### ISSUE THREAD

**Issue by Obsywon** [Obsywon/Escapade#32]

**Comment by CathDen** [comment]
en tant qu'utilisateur je veux voir comment chaque membre de l'équipe avait fait des recherches, travaillé sur les tutos, les difficultés rencontrées pour aboutir au choix finaux des ressources, des technos à utiliser pour développer l'application.

**Comment by TheoRousseau25** [comment]
En tant que développeur je souhaite avoir rapidement accès aux tutos qui pourraient être utiles au maintien de l'application ou à l'ajout de nouvels features ainsi que connaitre les principales étapes qui ont mené à l'élaboration de l'architecture
